### ISSUE TITLE
La foire des bug à corriger

### ISSUE THREAD

**Issue by philippesimard** [philippesimard/allies#19]
Salutation mon brave, 

Voici quelques bugs et choses à faire. 

-Pouvoir ce déconnecter en toute quiétude;
-Les nouveaux utilisateurs inscrit ne peuvent pas ajouter des médias correctement c'est instable. À vérifier;
-Les médias et les pistes doivent pouvoir être consultées par tous les utilisateurs non inscrit. Il faut retiriger les gens non inscrit vers la page de connextion;

Il faut se dire quand chacun travail  car je bosse presque tout le temps donc pour éviter les complis de synchronisation communication. 

Merci merci merci 

Philippe

**Comment by leseulsteve** [comment]
C'est fait, je propose de changer l'icône du coeur dans dans la fiche d'un média pour un coeur vide (outline) quand ce n'est pas ajouté dans les favoris et d'un coeur plein quand ce l'est et changer l'icone lors d'un hover pour indiquer que l'ont peut l'enlever des favoris.
