### ISSUE TITLE
Formulaire de contact zone utilisateur

### ISSUE THREAD

**Issue by philippesimard** [philippesimard/allies#2]
<h2> Formulaire de contact zone utilisateur: </h2>

Il sagit de pouvoir envoyer à partir de cette zone des couriels à l'adresse info@acommealliees.ca
Les informations de l'utilisateur comme son nom devrait être idéalement chargé à partir de son compte.

<img width="1413" alt="sans titre" src="https://cloud.githubusercontent.com/assets/13022531/9619907/b373c53a-50e2-11e5-875b-f3e725e39d49.png">

**Comment by leseulsteve** [comment]
On peut maintenant envoyer des messages par le formulaire de contact depuis 4c6ab752db54e5e04d918dfc957068345cf8317f.

Je t'invite à bien regarder ce commit afin de comprendre le fonctionnement de notre service de courriel :)

Sache que seulement les utilisateurs connectés peuvent l'utiliser afin d'éviter d'avoir des robots méchants qui l'utilisent.

Les courriels des destinataires sont configurés du côté serveur (voir backend/config/config.js). Cela fait en sorte que quelqu'un ne peux pas envoyer des courriels à d'autres destinataires.

Je ne fermerai pas cet 'issue' puisque le formulaire de contact aurait besoin d'un peu d'amour :). Je t'invite à prendre exemple sur le formulaire de création d'utilisateurs.
